---
title: "Sentiment Analysis of Tweets about Social Issues"
author: "Dana Westley"
date: "Due Sunday June 4, 2017"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#practicing tidy text and some simple sentiment analysis using only one days worth of data 
#source: https://cran.r-project.org/web/packages/tidytext/vignettes/tidytext.html
#more sources: http://juliasilge.com/blog/Life-Changing-Magic/
#more: https://stackoverflow.com/questions/43623400/how-to-add-custom-stop-word-list-to-stopwordsremover
#more: http://varianceexplained.org/r/trump-tweets/


library(purrr)
library(dplyr)
library(tidytext)
library(readr)
library(wordcloud)
library(tidyr)
library(ggplot2)

#RACE DATA
race_month <- read.csv("~/Desktop/Data Visualization/Westley Final Project/RaceMaster.csv")

race_month$text <- as.character(race_month$text)

tidy_month <- race_month %>%
  unnest_tokens(word, text)

data("stop_words")
nostopwords_monthdata <- tidy_month %>%
  anti_join(stop_words)

###MAYBE use tm to add custom stops? tidy text seems hard

nostopwords_monthdata %>% 
  count(word, sort = TRUE) %>%
  ungroup()

nostopwords_monthdata %>%
  count(word) %>%
  with(wordcloud(word, n, max.words = 100))

bing <- get_sentiments("bing")

sentiment_monthtweets <- tidy_month %>%
  inner_join(bing) %>%
  count(word, sentiment, sort = TRUE) %>%
  ungroup()

library(RColorBrewer)
race_all <- nostopwords_monthdata %>%
  count(word, sort = TRUE) %>%
  filter(n < 10000) %>%
  head(20) %>%
  mutate(word = reorder(word, n)) %>%
  ggplot(aes(word, n)) +
  geom_bar(stat = "identity") +
  labs(title = "Most Common Terms in Tweets \n About Race in Trump's First Month", x = "", y = "Mentions") + 
  theme_minimal() +
  scale_fill_manual(values = c("grey35", "grey70")) + 
  theme(axis.text.x = element_text(hjust = 1.0, size = 13, family = "Times"), 
        legend.title = element_blank(), 
        legend.text = element_text(family = "Times", size = 12), 
        plot.title = element_text(hjust = 0.5, size = 18, family = "Times"), 
        axis.text.y = element_text(family = "Times", size = 12), 
        axis.title.x = element_text(family = "Times", size = 15)) + 
  coord_flip()

race_posneg <- sentiment_monthtweets %>%
  filter(n > 750, n < 7500) %>%
  mutate(n = ifelse(sentiment == "negative", -n, n)) %>%
  mutate(word = reorder(word, n)) %>%
  ggplot(aes(word, n, fill = sentiment)) +
  geom_bar(stat = "identity") +
  labs(title = "Most Common Positive and Negative Words in Tweets \n About Race in Trump's First Month", x = "", y = "Mentions") + 
  theme_minimal() +
  scale_fill_manual(values = c("grey35", "grey70")) + 
  theme(axis.text.x = element_text(hjust = 1.0, size = 13, family = "Times"), 
        legend.title = element_blank(), 
        legend.text = element_text(family = "Times", size = 12), 
        plot.title = element_text(hjust = 0.5, size = 18, family = "Times"), 
        axis.text.y = element_text(family = "Times", size = 12), 
        axis.title.x = element_text(family = "Times", size = 15)) + 
  coord_flip()
  

#GENDER
gender_month <- read.csv("~/Desktop/Data Visualization/Westley Final Project/GenderMaster.csv")

gender_month$text <- as.character(gender_month$text)

tidy_gendermonth <- gender_month %>%
  unnest_tokens(word, text)

data("stop_words")
nostopwords_gendermonthdata <- tidy_gendermonth %>%
  anti_join(stop_words)

nostopwords_gendermonthdata %>% 
  count(word, sort = TRUE)

sentiment_gendermonthtweets <- tidy_gendermonth %>%
  inner_join(bing) %>%
  count(word, sentiment, sort = TRUE) %>%
  ungroup()

gender_all <- nostopwords_gendermonthdata %>%
  count(word, sort = TRUE) %>%
  filter(n < 10000) %>%
  head(20) %>%
  mutate(word = reorder(word, n)) %>%
  ggplot(aes(word, n)) +
  geom_bar(stat = "identity") +
  labs(title = "Most Common Terms in Tweets \n About Gender in Trump's First Month", x = "", y = "Mentions") + 
  theme_minimal() +
  theme(axis.text.x = element_text(hjust = 1.0, size = 13, family = "Times"), 
        legend.title = element_blank(), 
        legend.text = element_text(family = "Times", size = 12), 
        plot.title = element_text(hjust = 0.5, size = 18, family = "Times"), 
        axis.text.y = element_text(family = "Times", size = 12), 
        axis.title.x = element_text(family = "Times", size = 15)) + 
  coord_flip()

gender_posneg <- sentiment_gendermonthtweets %>%
  filter(n > 750, n < 10000) %>%
  mutate(n = ifelse(sentiment == "negative", -n, n)) %>%
  mutate(word = reorder(word, n)) %>%
  ggplot(aes(word, n, fill = sentiment)) +
  geom_bar(stat = "identity") +
  labs(title = "Most Common Positive and Negative Words in Tweets \n About Gender in Trump's First Month", x = "", y = "Mentions") + 
  theme_minimal() +
  scale_fill_manual(values = c("grey35", "grey70")) + 
  coord_flip() +
  theme(axis.text.x = element_text(hjust = 1.0, size = 13, family = "Times"), 
        legend.title = element_blank(), 
        legend.text = element_text(family = "Times", size = 12), 
        plot.title = element_text(hjust = 0.5, size = 18, family = "Times"), 
        axis.text.y = element_text(family = "Times", size = 12), 
        axis.title.x = element_text(family = "Times", size = 15))


#RELIGION
religion_month <- read.csv("~/Desktop/Data Visualization/Westley Final Project/ReligionMaster.csv")

religion_month$text <- as.character(religion_month$text)

tidy_religionmonth <- religion_month %>%
  unnest_tokens(word, text)

data("stop_words")
nostopwords_religionmonthdata <- tidy_religionmonth %>%
  anti_join(stop_words)

nostopwords_religionmonthdata %>% 
  count(word, sort = TRUE)

sentiment_religionmonthtweets <- tidy_religionmonth %>%
  inner_join(bing) %>%
  count(word, sentiment, sort = TRUE) %>%
  ungroup()

religion_all <- nostopwords_religionmonthdata %>%
  count(word, sort = TRUE) %>%
  filter(n < 15000) %>%
  head(20) %>%
  mutate(word = reorder(word, n)) %>%
  ggplot(aes(word, n)) +
  geom_bar(stat = "identity") +
  labs(title = "Most Common Terms in Tweets \n About Religion in Trump's First Month", x = "", y = "Mentions") + 
  theme_minimal() +
  theme(axis.text.x = element_text(hjust = 1.0, size = 13, family = "Times"), 
        legend.title = element_blank(), 
        legend.text = element_text(family = "Times", size = 12), 
        plot.title = element_text(hjust = 0.5, size = 18, family = "Times"), 
        axis.text.y = element_text(family = "Times", size = 12), 
        axis.title.x = element_text(family = "Times", size = 15)) + 
  coord_flip()

religion_posneg <- sentiment_religionmonthtweets %>%
  filter(n > 750, n < 6000) %>%
  mutate(n = ifelse(sentiment == "negative", -n, n)) %>%
  mutate(word = reorder(word, n)) %>%
  ggplot(aes(word, n, fill = sentiment)) +
  geom_bar(stat = "identity") +
  labs(title = "Most Common Positive and Negative Words in Tweets \n About Religion in Trump's First Month", x = "", y = "Mentions") + 
  theme_minimal() +
  scale_fill_manual(values = c("grey35", "grey70")) + 
  coord_flip() +
  theme(axis.text.x = element_text(hjust = 1.0, size = 13, family = "Times"), 
        legend.title = element_blank(), 
        legend.text = element_text(family = "Times", size = 12), 
        plot.title = element_text(hjust = 0.5, size = 18, family = "Times"), 
        axis.text.y = element_text(family = "Times", size = 12), 
        axis.title.x = element_text(family = "Times", size = 15))
```

#Most Common Terms in Tweets About: 
##Race
```{r, echo=FALSE}
print(race_all)
```

##Gender
```{r, echo=FALSE}
print(gender_all)
```

##Religion
```{r, echo=FALSE}
print(religion_all)
```


#Sentiment Analysis for Positive and Negative Words in Tweets About:
##Race
```{r, echo=FALSE}
print(race_posneg)
```

##Gender
```{r, echo=FALSE}
print(gender_posneg)
```

##Religion
```{r, echo=FALSE}
print(religion_posneg)
```



```{r, include=FALSE}
#playing with TIME/Duration Visuaization
#source: https://stackoverflow.com/questions/17658274/annual-monthly-or-daily-mean-for-irregular-time-series
#more: https://stackoverflow.com/questions/3777174/plotting-two-variables-as-lines-using-ggplot2-on-the-same-graph


race_month$created <- as.Date(race_month$created, "%m/%d/%y")

race_month$text <- as.character(race_month$text)
library(reshape2)
library(tidytext)
data("stop_words")
clean_racedata <- race_month %>%
  unnest_tokens(word, text)

data("stop_words")
nstopsracetime <- clean_racedata %>%
  anti_join(stop_words)

sent_racetime <- clean_racedata %>%
  inner_join(bing) %>%
  ungroup()


sent_racetime$positive[sent_racetime$sentiment == "positive"] = 1
sent_racetime$positive[sent_racetime$sentiment == "negative"] = 0
sent_racetime$positive <- factor(sent_racetime$positive, levels = c(0,1))

sent_racetime$negative[sent_racetime$sentiment == "negative"] = 1
sent_racetime$negative[sent_racetime$sentiment == "positive"] = 0
sent_racetime$negative <- factor(sent_racetime$negative, levels = c(0,1))


sent_racetime$created <- as.Date(sent_racetime$created, "%m/%d/%y")

dailymeans <- aggregate(cbind("positive.mean" = positive,
                "negative.mean" = negative) ~ created,
          data = sent_racetime,
          FUN = mean)

dailysums_race <- aggregate(cbind("positive.mean" = positive,
                "negative.mean" = negative) ~ created,
          data = sent_racetime,
          FUN = sum)

dailysums_race_long <- melt(dailysums_race, id = "created")

library(reshape2)
dailymeans_long <- melt(dailymeans, id = "created")

dailymeansplot <- ggplot(dailymeans_long, aes(created, value, color = variable)) + 
  geom_line() +
  theme_minimal() + 
  labs(title = "Daily Average of Positive & Negative Words \n for Tweets about Race", 
       x = "Date", y = "Average # of Words") + 
  guides(color=guide_legend("Sentiment")) + 
  theme(plot.title = element_text(hjust = 0.5, size = 18, family = "Times"), 
        axis.title = element_text(family = "Times", size = 13), 
        legend.text = element_text(family = "Times", size = 11), 
        legend.title = element_text(family = "Times", size = 12), 
        axis.text.x = element_text(family = "Times")) +
  scale_color_manual(values = c("Grey70", "Black"), labels = c("Positive", "Negative"))

dailysumssplot_race <- ggplot(dailysums_race_long, aes(created, value, color = variable)) + 
  geom_line() +
  theme_minimal() + 
  labs(title = "Daily Sum of Positive & Negative Words \n for Tweets about Race", 
       x = "Date", y = "Total # of Words") + 
  guides(color=guide_legend("Sentiment")) + 
  theme(plot.title = element_text(hjust = 0.5, size = 18, family = "Times"), 
        axis.title = element_text(family = "Times", size = 13), 
        legend.text = element_text(family = "Times", size = 11), 
        legend.title = element_text(family = "Times", size = 12), 
        axis.text.x = element_text(family = "Times")) +
  scale_color_manual(values = c("Grey70", "Black"), labels = c("Positive", "Negative"))

#Gender over time
sent_gendertime <- tidy_gendermonth %>%
  inner_join(bing) %>%
  ungroup()


sent_gendertime$positive[sent_gendertime$sentiment == "positive"] = 1
sent_gendertime$positive[sent_gendertime$sentiment == "negative"] = 0
sent_gendertime$positive <- factor(sent_gendertime$positive, levels = c(0,1))

sent_gendertime$negative[sent_gendertime$sentiment == "negative"] = 1
sent_gendertime$negative[sent_gendertime$sentiment == "positive"] = 0
sent_gendertime$negative <- factor(sent_gendertime$negative, levels = c(0,1))


sent_gendertime$created <- as.Date(sent_gendertime$created, "%m/%d/%y")

dailymeans_gen <- aggregate(cbind("positive.mean" = positive,
                "negative.mean" = negative) ~ created,
          data = sent_gendertime,
          FUN = mean)

dailymeans_gen_long <- melt(dailymeans_gen, id = "created")

dailymeansplot_gen <- ggplot(dailymeans_gen_long, aes(created, value, color = variable)) + 
  geom_line() +
  theme_minimal() + 
  labs(title = "Daily Average of Positive & Negative Words \n for Tweets about Gender", 
       x = "Date", y = "Average # of Words") + 
  guides(color=guide_legend("Sentiment")) + 
  theme(plot.title = element_text(hjust = 0.5, size = 18, family = "Times"), 
        axis.title = element_text(family = "Times", size = 13), 
        legend.text = element_text(family = "Times", size = 11), 
        legend.title = element_text(family = "Times", size = 12), 
        axis.text.x = element_text(family = "Times")) +
  scale_color_manual(values = c("Grey70", "Black"), labels = c("Positive", "Negative"))

#Religion over time
sent_religiontime <- tidy_religionmonth %>%
  inner_join(bing) %>%
  ungroup()


sent_religiontime$positive[sent_religiontime$sentiment == "positive"] = 1
sent_religiontime$positive[sent_religiontime$sentiment == "negative"] = 0
sent_religiontime$positive <- factor(sent_religiontime$positive, levels = c(0,1))

sent_religiontime$negative[sent_religiontime$sentiment == "negative"] = 1
sent_religiontime$negative[sent_religiontime$sentiment == "positive"] = 0
sent_religiontime$negative <- factor(sent_religiontime$negative, levels = c(0,1))


sent_religiontime$created <- as.Date(sent_religiontime$created, "%m/%d/%y")

dailymeans_rel <- aggregate(cbind("positive.mean" = positive,
                "negative.mean" = negative) ~ created,
          data = sent_religiontime,
          FUN = mean)

dailymeans_rel_long <- melt(dailymeans_rel, id = "created")

dailymeansplot_rel <- ggplot(dailymeans_rel_long, aes(created, value, color = variable)) + 
  geom_line() +
  theme_minimal() + 
  labs(title = "Daily Average of Positive & Negative Words \n for Tweets about Religion", 
       x = "Date", y = "Average # of Words") + 
  guides(color=guide_legend("Sentiment")) + 
  theme(plot.title = element_text(hjust = 0.5, size = 18, family = "Times"), 
        axis.title = element_text(family = "Times", size = 13), 
        legend.text = element_text(family = "Times", size = 11), 
        legend.title = element_text(family = "Times", size = 12), 
        axis.text.x = element_text(family = "Times")) +
  scale_color_manual(values = c("Grey70", "Black"), labels = c("Positive", "Negative"))



dailysums_gen <- aggregate(cbind("positive.mean" = positive,
                "negative.mean" = negative) ~ created,
          data = sent_gendertime,
          FUN = sum)

dailysums_gen_long <- melt(dailysums_gen, id = "created")

dailysumssplot_gen <- ggplot(dailysums_gen_long, aes(created, value, color = variable)) + 
  geom_line() +
  theme_minimal() + 
  labs(title = "Daily Sum of Positive & Negative Words \n for Tweets about Gender", 
       x = "Date", y = "Total # of Words") + 
  guides(color=guide_legend("Sentiment")) + 
  theme(plot.title = element_text(hjust = 0.5, size = 18, family = "Times"), 
        axis.title = element_text(family = "Times", size = 13), 
        legend.text = element_text(family = "Times", size = 11), 
        legend.title = element_text(family = "Times", size = 12), 
        axis.text.x = element_text(family = "Times")) +
  scale_color_manual(values = c("Grey70", "Black"), labels = c("Positive", "Negative"))


dailysums_rel <- aggregate(cbind("positive.mean" = positive,
                "negative.mean" = negative) ~ created,
          data = sent_religiontime,
          FUN = sum)

dailysums_rel_long <- melt(dailysums_rel, id = "created")

dailysumsplot_rel <- ggplot(dailysums_rel_long, aes(created, value, color = variable)) + 
  geom_line() +
  theme_minimal() + 
  labs(title = "Daily Sum of Positive & Negative Words \n for Tweets about Religion", 
       x = "Date", y = "Total # of Words") + 
  guides(color=guide_legend("Sentiment")) + 
  theme(plot.title = element_text(hjust = 0.5, size = 18, family = "Times"), 
        axis.title = element_text(family = "Times", size = 13), 
        legend.text = element_text(family = "Times", size = 11), 
        legend.title = element_text(family = "Times", size = 12), 
        axis.text.x = element_text(family = "Times")) +
  scale_color_manual(values = c("Grey70", "Black"), labels = c("Positive", "Negative"))


#NET POSITIVITY
dailysums_rel$netPositve <- (dailysums_rel$positive.mean - dailysums_rel$negative.mean)

dailysums_gen$netPositve <- (dailysums_gen$positive.mean - dailysums_gen$negative.mean)

dailysums_race$netPositve <- (dailysums_race$positive.mean - dailysums_race$negative.mean)

#MERGE NET POSITIVITY AND TRACK SOURCE DF
dailysums_rel$Issue <- "religion"

dailysums_gen$Issue <- "gender"

dailysums_race$Issue <- "race"



#BIND
netdf <- rbind(dailysums_gen, dailysums_race, dailysums_rel)


#plot net
netSentplot <- ggplot(netdf, aes(created, netPositve, color = Issue)) + 
  geom_smooth() +
  theme_minimal() + 
  labs(title = "Net Daily Positivity Score for Tweets by Issue", 
       x = "Date", y = "Net Positivity") + 
  guides(color=guide_legend("Sentiment")) + 
  theme(plot.title = element_text(hjust = 0.5, size = 18, family = "Times"), 
        axis.title = element_text(family = "Times", size = 13), 
        legend.text = element_text(family = "Times", size = 11), 
        legend.title = element_text(family = "Times", size = 12), 
        axis.text.x = element_text(family = "Times"))

```


#Sentiment of Race Tweets Over Time
``` {r, echo = FALSE}
print(dailymeansplot)

print(dailymeansplot_gen)

print(dailymeansplot_rel)

```

#Using Sums instead of Means
``` {r, echo = FALSE}

print(dailysumssplot_race)

print(dailysumssplot_gen)

print(dailysumsplot_rel)

```

#Net Positivity

``` {r, echo = FALSE}
print(netSentplot)

```